"""Emulator bridges: launching an emulator on a ROM with one of capture's
scripts.

A bridge knows one emulator: how to launch it in each of three roles — the
recorder (headed, the user's), the replay and the probe server (both headless)
— and how the script it loads names a path. mapchar never links an emulator;
the user's own install is started as a process. The built-in bridge is Mesen 2,
which covers every console with a profile in :mod:`mapchar.capture.consoles`.
"""

from __future__ import annotations

import os
import platform
import shutil
import subprocess
from importlib import resources
from typing import Protocol

from mapchar.capture.consoles import Console, lua_value

RECORDER = "recorder"
REPLAY = "replay"
PROBE = "probe"
ROLES = (RECORDER, REPLAY, PROBE)

HEADLESS_TIMEOUT = 100000
"""Seconds a headless run may take before the emulator gives up on its own;
mapchar's own deadlines are far shorter."""


def script_source(name: str) -> str:
    return (
        resources.files("mapchar.capture")
        .joinpath("scripts", f"{name}.lua")
        .read_text(encoding="utf-8")
    )


def build_script(role: str, console: Console, settings: dict) -> str:
    """The script for a role: the console's facts and the role's settings as
    ``CFG``, the shared prelude, then the role's own part."""
    cfg = {**console.config(), **settings}
    return "\n".join(
        [
            f"-- generated by mapchar for the {role}",
            f"CFG = {lua_value(cfg)}",
            script_source("common"),
            script_source(role),
        ]
    )


class Emulator(Protocol):
    id: str
    name: str

    def consoles(self) -> tuple[str, ...]: ...

    def available(self) -> bool: ...

    def native_path(self, path: str) -> str:
        """``path`` as the emulator's scripts must spell it."""
        ...

    def launch(
        self, rom: str, role: str, script: str, log: str | None = None
    ) -> subprocess.Popen: ...


def _in_wsl() -> bool:
    return "microsoft" in platform.release().lower()


class Mesen:
    """Mesen 2: every setting a launch needs is a switch, so the user's own
    settings are never edited."""

    id = "mesen2"
    name = "Mesen 2"

    def __init__(self, path: str | None = None):
        self.path = path or self.find()

    @staticmethod
    def find() -> str | None:
        for name in ("mesen", "Mesen", "Mesen.exe"):
            found = shutil.which(name)
            if found:
                return found
        return None

    def consoles(self) -> tuple[str, ...]:
        return ("snes-lorom", "snes-hirom", "snes-superfx", "nes", "gba")

    def available(self) -> bool:
        return bool(self.path) and os.path.isfile(self.path)

    @property
    def windows_from_wsl(self) -> bool:
        return bool(self.path) and self.path.lower().endswith(".exe") and _in_wsl()

    def native_path(self, path: str) -> str:
        path = os.path.abspath(path)
        if self.windows_from_wsl:
            return subprocess.run(
                ["wslpath", "-w", path], capture_output=True, text=True, check=True
            ).stdout.strip()
        return path

    def arguments(self, rom: str, role: str, script: str) -> list[str]:
        args = [
            self.native_path(rom),
            self.native_path(script),
            "--doNotSaveSettings",
            "--debug.scriptWindow.allowIoOsAccess=true",
            "--debug.scriptWindow.allowNetworkAccess=true",
        ]
        if role == RECORDER:
            # A second launch would otherwise hand its ROM to a window already open.
            args.append("--preferences.singleInstance=false")
        else:
            args += [
                "--testRunner",
                "--enablestdout",
                f"--timeout={HEADLESS_TIMEOUT}",
                "--debug.scriptWindow.scriptTimeout=30",
            ]
        return [self.path or "mesen", *args]

    def launch(
        self, rom: str, role: str, script: str, log: str | None = None
    ) -> subprocess.Popen:
        if not self.available():
            raise FileNotFoundError("Mesen 2 was not found; set its path in Capture")
        env = dict(os.environ)
        if role != RECORDER:
            # Headless: nothing may reach a display, WSLg's included.
            env.pop("DISPLAY", None)
            env.pop("WAYLAND_DISPLAY", None)
        out = open(log, "w") if log else subprocess.DEVNULL  # noqa: SIM115
        kwargs = {}
        if os.name == "nt" and role != RECORDER:
            kwargs["creationflags"] = subprocess.CREATE_NO_WINDOW
        try:
            return subprocess.Popen(
                self.arguments(rom, role, script),
                env=env,
                stdout=out,
                stderr=subprocess.STDOUT,
                stdin=subprocess.DEVNULL,
                **kwargs,
            )
        finally:
            if log:
                out.close()


EMULATORS = {Mesen.id: Mesen}
